name: KRandomTeleport
version: ${project.version}

git_repo: https://github.com/Samistine/KRandomTeleport
git_hash: ${git_hash}
jenkins_build: ${BUILD_NUMBER}

main: com.kmcguire.krandomteleport.KRandomTeleport
authors: [Leonard Kevin McGuire Jr]
softdepend: [Herochat]